#!/usr/bin/awk -f
BEGIN {
	# ARGV[0] is the filename of the script itself.
	#ARGV[1] = "ab.txt"
    ARGV[1] = "研究社新和英大辞典第５版.txt"
    # Set ARGV length.
    ARGC = 2
    
}

BEGIN { 
	pat = "安くなります" 
	reg = "ではありませんでした"
}

$0 ~ pat {print; print FNR; print length($0)}  # FNR 当前行数
$0 ~ reg {print}
END { print NR }

